version: "3"
services:
  db:
    image: quay.io/maksymbilenko/oracle-12c:latest
    volumes:
      - oracle:/u01/app/oracle
    ports:
      - 1521:1521
    hostname: oracle
    networks:
      - shop
