CREATE TABLE USER
(
    ID NUMBER(19)  NOT NULL PRIMARY KEY,
    FIRST_NAME NVARCHAR2(256),
    LAST_NAME NVARCHAR2(256),
    USERNAME VARCHAR(128),
    PASSWORD VARCHAR(512),
    EMAIL VARCHAR(256),
    MOBILE_NUMBER VARCHAR(64),
);